package com.creatorfromhell.core.uapi.attribute;

public enum AttributeType {
  // General
  GENERIC_MAX_HEALTH, GENERIC_FOLLOW_RANGE, GENERIC_KNOCKBACK_RESISTANCE, GENERIC_MOVEMENT_SPEED, GENERIC_ATTACK_DAMAGE, GENERIC_ARMOR, GENERIC_ARMOR_TOUGHNESS,

  // Player
  GENERIC_ATTACK_SPEED, GENERIC_LUCK,

  // Horses
  HORCE_JUMP_STRENGTH,

  // Zombies
  ZOMBIE_SPAWN_REINFORCEMENTS,
}